version: '3.4'

services:
  common.webapicore:
    image: commonwebapicore:runtime
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    ports:
       - "8080:80"
    restart: always

  db:
    image: postgres
    environment:
       POSTGRES_USER: filmadviseradmin
       POSTGRES_PASSWORD: filmadviseradminpassw1
       POSTGRES_DB: filmadviser
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    restart: always
   
  redis:
    image: redis
    restart: always
       
volumes:
  database-data: